FROM caddy:latest

# Since the root directory is set to 'caddy', the build context is already inside the caddy folder.
# We just need to copy 'Caddyfile' (which is in the same folder as this Dockerfile)
COPY Caddyfile /etc/caddy/Caddyfile
